### ISSUE TITLE
Bad results from compression

### ISSUE THREAD

**Issue by arcman7** [KeKsBoTer/c3dgs#11]
Great work overall! This is a really great start to having 3DGS models be more portable for the web. However, I've encountered some issues while testing this compression technique with custom data - my own .ply files-

The .ply splat model rendering:
![image](https://github.com/user-attachments/assets/9500da71-0b48-48fb-b8ca-59410da92181)

The .npz compression model rendering:
![image](https://github.com/user-attachments/assets/41ae9fd2-4baa-4389-948a-120e652c7c0a)

Not sure I understand what went wrong - cloned the repo and ran the command against the .ply file. ~~Did you guys use more iterations than the hard-coded defaults to produce the results shown in the examples?~~

After testing, it seems like running more finetune iterations yields worse results in terms of the visual representation.

**Comment by KeKsBoTer** [comment]
Thanks for your interest! 
I tuned the hyperparameters for the datasets in the paper. Your scene might be different (e.g.larger) and require different values.

First, try do adjust which gaussian get quantized with the `color_importance_include` and `gaussian_importance_include` parameters. If you decrease these values, the compression will be less aggressive, but give better results.  

You can also try to increase the codebook sizes with `--gaussian_codebook_size <size>` and `--color_codebook_size <size>`.
