### ISSUE TITLE
AssertionError: Could not recognize scene type!

### ISSUE THREAD

**Issue by oneChubby** [KeKsBoTer/c3dgs#14]
Traceback (most recent call last):
  File "compress.py", line 265, in <module>
    run_vq(model_params, optim_params, pipeline_params, comp_params)
  File "compress.py", line 131, in run_vq
    scene = Scene(
  File "/home/Project/c3dgs/scene/__init__.py", line 64, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!

**Comment by Ira569** [comment]
just use the original 3d gaussian splatting to train a scene,and model_folder is in gaussian splatting's output folder,I tried,it works.
python compress.py --model_path <model_folder> --data_device "cuda" --output_vq <output_folder>

**Comment by oneChubby** [comment]
Thanks for your answer, I've fixed the issue, but I found that the metrics were not working properly after the training was completed
![image](https://github.com/user-attachments/assets/d6fe6b75-ecde-4e8b-a33c-b66667b649a9)

**Comment by oneChubby** [comment]
Thank you very much for your answer, I've fixed this issue
