### ISSUE TITLE
Confused with the type of index

### ISSUE THREAD

**Issue by moqiyinlun** [KeKsBoTer/c3dgs#7]
Why the codebook size is 2**12 but in the paper you say you use a uint32 to store it? Maybe uint16 is enough

**Comment by KeKsBoTer** [comment]
The codebooks have a size of 2**12 per default. However, we also store the indices to the Gaussian and SH parameters, which we do not quantize (keep). Then uint16 is not enough anymore. In practice, the entropy encoding reduces everything to the required number of bits for storage.

**Comment by moqiyinlun** [comment]
Oh I see, if you separate the cluster center of the attribute and the index of the attribute to store, you can use uint16 to store the index?

**Comment by KeKsBoTer** [comment]
Yes, that is correct.
